# Hadolint configuration
  failure-threshold: error  # csak ERROR vagy súlyosabb dobja el a CI-t

override:
  info:
    - DL3008  # apt-get install verziópin
    - DL3013  # pip install verziópin
    - SC1091  # ShellCheck: "Not following: ..." (source)

# Trusted registries
trustedRegistries:
  - docker.io
  - registry.hub.docker.com