version: '3.8'

# Development overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  app:
    build:
      target: development
    environment:
      - LOG_LEVEL=DEBUG
      - PYTHONPATH=/app
    volumes:
      - ./src:/app/src:rw  # Enable hot reload
      - ./scripts:/app/scripts:rw
    command: >
      uvicorn src.inference.app:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app/src
      --log-level debug

  # Disable resource limits in development
  db:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    
  redis:
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M