[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "legalqa"
version = "0.1.0"
description = "Legal Question Answering System"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
dependencies = [
    "langchain",
    "langchain-openai",
    "faiss-cpu",
    "pandas",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
    "mypy",
]

[tool.black]
line-length = 88
target-version = ["py38"]

[tool.isort]
profile = "black"
multi_line_output = 3 