apiVersion: apps/v1
kind: Deployment
metadata:
  name: legalqa-canary
  labels:
    app: legalqa
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legalqa
      version: canary
  template:
    metadata:
      labels:
        app: legalqa
        version: canary
    spec:
      containers:
      - name: legalqa
        image: legalqa:canary
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: "db"
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        - name: CANARY_MODE
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: legalqa-canary-service
spec:
  selector:
    app: legalqa
    version: canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: legalqa-canary-ingress
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  rules:
  - host: legalqa.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: legalqa-canary-service
            port:
              number: 80 