global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # LegalQA Application (host.docker.internal for testing)
  - job_name: 'legalqa'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL Database (host.docker.internal for testing)
  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:5433']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis Cache (host.docker.internal for testing)
  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:6379']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']